from PyQt6 import QtCore, QtGui, QtWidgets


class Scroll_button():
    def __init__(self, scrollAreaWidgetContents, verticalLayout_4,hdébut,hfin,adresse,PriceAdult,PriceChild,PlaceAvailableAdult,PlaceAvailableChild,ID_ACT):   
        self.ID_ACT = ID_ACT
        self.widget = QtWidgets.QWidget(parent=scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(100, 110, 471, 151))
        self.widget.setMinimumSize(QtCore.QSize(471, 151))
        self.widget.setMaximumSize(QtCore.QSize(471, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setStyleSheet("background-color:rgb(36, 37, 130);\n"
"border-radius:25px;\n"
"\n"
"color:white;\n"
"font-weight:bold;\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 321, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 20, 141, 61))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 32pt \"Arial\";\n"
"border-radius: 30px;\n"
"\n"
"color: black;\n"
"font-weight:bold;")
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(210, 0, 251, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(parent=self.frame_2)
        self.widget_4.setMinimumSize(QtCore.QSize(234, 83))
        self.widget_4.setStyleSheet("color:white;\n"
"font-weight:bold;")
        self.widget_4.setObjectName("widget_4")
        self.lab13_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab13_5.setGeometry(QtCore.QRect(110, 0, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab13_5.setFont(font)
        self.lab13_5.setObjectName("lab13_5")
        self.lab22_8 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab22_8.setGeometry(QtCore.QRect(130, 30, 55, 16))
        self.lab22_8.setMaximumSize(QtCore.QSize(55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab22_8.setFont(font)
        self.lab22_8.setObjectName("lab22_8")
        self.line_18 = QtWidgets.QFrame(parent=self.widget_4)
        self.line_18.setGeometry(QtCore.QRect(120, 50, 91, 3))
        self.line_18.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_18.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.line_18.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(parent=self.widget_4)
        self.line_19.setGeometry(QtCore.QRect(120, 20, 91, 3))
        self.line_19.setMaximumSize(QtCore.QSize(16777215, 3))
        self.line_19.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.line_19.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(parent=self.widget_4)
        self.line_20.setGeometry(QtCore.QRect(120, 10, 3, 61))
        self.line_20.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.line_20.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_20.setObjectName("line_20")
        self.lab22_7 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab22_7.setGeometry(QtCore.QRect(130, 60, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab22_7.setFont(font)
        self.lab22_7.setObjectName("lab22_7")
        self.line_22 = QtWidgets.QFrame(parent=self.widget_4)
        self.line_22.setGeometry(QtCore.QRect(60, 10, 3, 61))
        self.line_22.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.line_22.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_21 = QtWidgets.QFrame(parent=self.widget_4)
        self.line_21.setGeometry(QtCore.QRect(10, 50, 118, 3))
        self.line_21.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.line_21.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_17 = QtWidgets.QFrame(parent=self.widget_4)
        self.line_17.setGeometry(QtCore.QRect(10, 20, 118, 3))
        self.line_17.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.line_17.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_17.setObjectName("line_17")
        self.lab11_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab11_5.setGeometry(QtCore.QRect(10, 0, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab11_5.setFont(font)
        self.lab11_5.setObjectName("lab11_5")
        self.lab12_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab12_5.setGeometry(QtCore.QRect(60, 0, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab12_5.setFont(font)
        self.lab12_5.setObjectName("lab12_5")
        self.lab22_6 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab22_6.setGeometry(QtCore.QRect(70, 30, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab22_6.setFont(font)
        self.lab22_6.setObjectName("lab22_6")
        self.lab22_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab22_5.setGeometry(QtCore.QRect(70, 60, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab22_5.setFont(font)
        self.lab22_5.setObjectName("lab22_5")
        self.lab31_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab31_5.setGeometry(QtCore.QRect(20, 60, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab31_5.setFont(font)
        self.lab31_5.setObjectName("lab31_5")
        self.lab21_5 = QtWidgets.QLabel(parent=self.widget_4)
        self.lab21_5.setGeometry(QtCore.QRect(20, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lab21_5.setFont(font)
        self.lab21_5.setObjectName("lab21_5")
        self.gridLayout.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(parent=self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 2, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(parent=self.frame)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 451, 101))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.toolButton.setStyleSheet("background:transparent;")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.frame)
        verticalLayout_4.addWidget(self.widget)
        

  
        self.label_5.setText(f"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">{hdébut}h - {hfin}h</span></p></body></html>")
        self.label_6.setText(f"<html><head/><body><p><span style=\" font-size:10pt;\">Lieu : {adresse}</span></p></body></html>")
        self.pushButton.setText("Confirme")
        self.lab13_5.setText("<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">Place available</span></p></body></html>")
        self.lab22_8.setText(f"<html><head/><body><p><span style=\" font-weight:400;\">{PlaceAvailableChild}</span></p></body></html>")                      #HD
        self.lab22_7.setText(f"<html><head/><body><p><span style=\" font-weight:400;\">{PlaceAvailableAdult}</span></p></body></html>")                      #BD
        self.lab11_5.setText("<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">Age</span></p></body></html>")
        self.lab12_5.setText("<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">Price</span></p></body></html>")
        self.lab22_6.setText(f"<html><head/><body><p><span style=\" font-weight:400;\">{PriceChild}</span></p></body></html>")                      #HG
        self.lab22_5.setText(f"<html><head/><body><p><span style=\" font-weight:400;\">{PriceAdult}</span></p></body></html>")                      #BG
        self.lab31_5.setText("<html><head/><body><p><span style=\" font-weight:400;\">Adult</span></p></body></html>")
        self.lab21_5.setText("<html><head/><body><p><span style=\" font-weight:400;\">Child</span></p></body></html>")




class Scroll_button2():
        def __init__(self, scrollAreaWidgetContents, verticalLayout_4,x,y ):
                
            self.widget_2 = QtWidgets.QWidget(parent=scrollAreaWidgetContents)
            self.widget_2.setGeometry(QtCore.QRect(290, 150, 421, 141))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.widget_2.setFont(font)
            self.widget_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
            self.widget_2.setStyleSheet("color:white;\n"
    "font-weight:bold;\n")
    
            self.widget_2.setObjectName("widget_2")
            self.toolButton = QtWidgets.QToolButton(parent=self.widget_2)
            self.toolButton.setGeometry(QtCore.QRect(0, 10, 421, 131))
            font = QtGui.QFont()
            font.setBold(True)
            font.setWeight(75)
            self.toolButton.setFont(font)
            self.toolButton.setStyleSheet("background-color: rgb(11, 107, 159);\n"
    "border-radius:25px;\n"
    "\n"
    "color:white;")
            self.toolButton.setText("")
            self.toolButton.setObjectName("toolButton")
            self.label = QtWidgets.QLabel(parent=self.widget_2)
            self.label.setGeometry(QtCore.QRect(20, 20, 141, 61))
            self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
    "font: 75 32pt \"Arial\";\n"
    "border-radius: 30px;\n"
    "\n"
    "color: black;\n"
    "font-weight:bold;")
            self.label.setObjectName("label")
            self.adresse = QtWidgets.QLabel(parent=self.widget_2)
            self.adresse.setGeometry(QtCore.QRect(20, 100, 251, 16))
            self.adresse.setStyleSheet("font: 75 10pt \"Arial\";\n"
                                       "font-weight:bold;")

            
        





            self.adresse.setObjectName("adresse")
            self.lab12 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab12.setGeometry(QtCore.QRect(240, 30, 55, 16))
            self.lab12.setObjectName("lab12")
            self.line = QtWidgets.QFrame(parent=self.widget_2)
            self.line.setGeometry(QtCore.QRect(190, 40, 221, 20))
            self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
            self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
            self.line.setObjectName("line")
            self.line_2 = QtWidgets.QFrame(parent=self.widget_2)
            self.line_2.setGeometry(QtCore.QRect(240, 30, 3, 61))
            self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
            self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
            self.line_2.setObjectName("line_2")
            self.line_3 = QtWidgets.QFrame(parent=self.widget_2)
            self.line_3.setGeometry(QtCore.QRect(190, 60, 221, 20))
            self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
            self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
            self.line_3.setObjectName("line_3")
            self.lab13 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab13.setGeometry(QtCore.QRect(290, 30, 111, 21))
            self.lab13.setObjectName("lab13")
            self.line_4 = QtWidgets.QFrame(parent=self.widget_2)
            self.line_4.setGeometry(QtCore.QRect(290, 30, 3, 61))
            self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
            self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
            self.line_4.setObjectName("line_4")
            self.lab11 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab11.setGeometry(QtCore.QRect(180, 30, 55, 16))
            self.lab11.setObjectName("lab11")
            self.lab21 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab21.setGeometry(QtCore.QRect(190, 50, 55, 16))
            self.lab21.setObjectName("lab21")
            self.lab31 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab31.setGeometry(QtCore.QRect(190, 70, 55, 16))
            self.lab31.setObjectName("lab31")
            self.lab22 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab22.setGeometry(QtCore.QRect(240, 50, 55, 16))
            self.lab22.setObjectName("lab22")
            self.lab23 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab23.setGeometry(QtCore.QRect(320, 50, 55, 16))
            self.lab23.setObjectName("lab23")
            self.lab32 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab32.setGeometry(QtCore.QRect(240, 70, 55, 16))
            self.lab32.setMaximumSize(QtCore.QSize(16777207, 16777215))
            self.lab32.setObjectName("lab32")
            self.lab33 = QtWidgets.QLabel(parent=self.widget_2)
            self.lab33.setGeometry(QtCore.QRect(320, 70, 55, 16))
            self.lab33.setObjectName("lab33")
            # Add the following code
            self.lab12.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab13.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab11.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab21.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab31.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab22.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab23.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab32.setStyleSheet("background-color:rgb(11, 107, 159);")
            self.lab33.setStyleSheet("background-color:rgb(11, 107, 159);")
            verticalLayout_4.addWidget(self.widget_2)
            self.label.setText("<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hdébut - Hfin</span></p></body></html>")
            self.adresse.setText("Lieu : 10 rue des vaguelettes")
            self.lab12.setText("<html><head/><body><p align=\"center\">Prix</p></body></html>")
            self.lab13.setText("<html><head/><body><p align=\"center\">Place Disponible</p></body></html>")
            self.lab11.setText("<html><head/><body><p align=\"center\">Age</p></body></html>")
            self.lab21.setText(f"{x}")
            self.lab31.setText("Adulte")
            self.lab22.setText("TextLabel")
            self.lab23.setText("TextLabel")
            self.lab32.setText("TextLabel")
            self.lab33.setText("<html><head/><body><p><span style=\" color:#ffffff;\">TextLabel</span></p></body></html>")
