# Form implementation generated from reading ui file 'ui_main3.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon, QPixmap, QImage
import resource
from ui_CustomButton import Scroll_button


class UiMainWindow(object):
    def setupUi(self, PAGES):
        PAGES.setObjectName("PAGES")
        PAGES.resize(989, 751)
        self.centralwidget = QtWidgets.QWidget(parent=PAGES)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.LIVRE = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.LIVRE.setAutoFillBackground(False)
        self.LIVRE.setStyleSheet("background:#242582")
        self.LIVRE.setObjectName("LIVRE")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("background-image: none\n"
"")
        self.page_1.setObjectName("page_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.page_1)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_17 = QtWidgets.QFrame(parent=self.widget)
        self.frame_17.setStyleSheet("\n"
"background-image: transparent\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label = QtWidgets.QLabel(parent=self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(85, 170, 255)\n"
"")
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(parent=self.frame_17)
        self.line_2.setStyleSheet("background-color:rgb(63, 66, 232)")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_10.addWidget(self.line_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(parent=self.widget)
        self.frame_18.setStyleSheet("background-color: rgb(36, 37, 130);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_18)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 941, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(44)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"    background-color: #F64C72;\n"
"    border: none;\n"
"    color:white;\n"
"    padding-top: 40px;\n"
"border-radius: 50px;\n"
"padding-bottom: 40px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(207, 64, 97);\n"
"}\n"
"\n"
"Color: light-grey;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/arbre.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(64, 64))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame_18)
        self.frame_31 = QtWidgets.QFrame(parent=self.widget)
        self.frame_31.setStyleSheet("background-color: none")
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_31)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(85, 170, 255)")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_21.addWidget(self.label_3, 2, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(parent=self.frame_31)
        self.line_7.setStyleSheet("background-color:rgb(63, 66, 232)")
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_21.addWidget(self.line_7, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(parent=self.widget)
        self.frame_32.setStyleSheet("background-color: none")
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.YoutubeBtn = QtWidgets.QPushButton(parent=self.frame_32)
        self.YoutubeBtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:rgb(63, 66, 232);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        self.YoutubeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/youtube.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.YoutubeBtn.setIcon(icon1)
        self.YoutubeBtn.setIconSize(QtCore.QSize(32, 32))
        self.YoutubeBtn.setObjectName("YoutubeBtn")
        self.horizontalLayout.addWidget(self.YoutubeBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.InstagramBtn = QtWidgets.QPushButton(parent=self.frame_32)
        self.InstagramBtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:rgb(63, 66, 232);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        self.InstagramBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/instagram.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.InstagramBtn.setIcon(icon2)
        self.InstagramBtn.setIconSize(QtCore.QSize(32, 32))
        self.InstagramBtn.setObjectName("InstagramBtn")
        self.horizontalLayout.addWidget(self.InstagramBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_32)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:rgb(63, 66, 232);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/linkedin.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.twitchBtn = QtWidgets.QPushButton(parent=self.frame_32)
        self.twitchBtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:rgb(63, 66, 232);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        self.twitchBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/twitch.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.twitchBtn.setIcon(icon4)
        self.twitchBtn.setIconSize(QtCore.QSize(32, 32))
        self.twitchBtn.setObjectName("twitchBtn")
        self.horizontalLayout.addWidget(self.twitchBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.frame_32)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.LIVRE.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.widget_16 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.frame_3 = QtWidgets.QFrame(parent=self.widget_16)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.leftside = QtWidgets.QWidget(parent=self.frame_3)
        self.leftside.setMinimumSize(QtCore.QSize(441, 531))
        self.leftside.setStyleSheet("background-color:rgba(85, 170, 255,200);border-radius:40px;")
        self.leftside.setObjectName("leftside")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.leftside)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.leftw2_2 = QtWidgets.QWidget(parent=self.leftside)
        self.leftw2_2.setMinimumSize(QtCore.QSize(419, 158))
        self.leftw2_2.setMaximumSize(QtCore.QSize(419, 158))
        self.leftw2_2.setObjectName("leftw2_2")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.leftw2_2)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.nom_2 = QtWidgets.QLineEdit(parent=self.leftw2_2)
        self.nom_2.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.nom_2.setFont(font)
        self.nom_2.setStyleSheet("background-color: #FFFFFF;")
        self.nom_2.setText("")
        self.nom_2.setObjectName("nom_2")
        self.gridLayout_36.addWidget(self.nom_2, 2, 0, 1, 1)
        self.emailsu_2 = QtWidgets.QLineEdit(parent=self.leftw2_2)
        self.emailsu_2.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.emailsu_2.setFont(font)
        self.emailsu_2.setStyleSheet("background-color: #FFFFFF;")
        self.emailsu_2.setObjectName("emailsu_2")
        self.gridLayout_36.addWidget(self.emailsu_2, 3, 0, 1, 1)
        self.mdpsu_2 = QtWidgets.QLineEdit(parent=self.leftw2_2)
        self.mdpsu_2.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.mdpsu_2.setFont(font)
        self.mdpsu_2.setStyleSheet("background-color: #FFFFFF;")
        self.mdpsu_2.setObjectName("mdpsu_2")
        self.gridLayout_36.addWidget(self.mdpsu_2, 4, 0, 1, 1)
        self.prenom_2 = QtWidgets.QLineEdit(parent=self.leftw2_2)
        self.prenom_2.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.prenom_2.setFont(font)
        self.prenom_2.setStyleSheet("background-color: #FFFFFF;")
        self.prenom_2.setClearButtonEnabled(False)
        self.prenom_2.setObjectName("prenom_2")
        self.gridLayout_36.addWidget(self.prenom_2, 1, 0, 1, 1)
        self.textevert = QtWidgets.QLabel(parent=self.leftw2_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.textevert.setFont(font)
        self.textevert.setStyleSheet("color:rgb(0, 255, 127);background-color: none;")
        self.textevert.setObjectName("textevert")
        self.gridLayout_36.addWidget(self.textevert, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.leftw2_2, 2, 0, 1, 1)
        self.leftw1_2 = QtWidgets.QWidget(parent=self.leftside)
        self.leftw1_2.setMinimumSize(QtCore.QSize(419, 183))
        self.leftw1_2.setMaximumSize(QtCore.QSize(419, 183))
        self.leftw1_2.setObjectName("leftw1_2")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.leftw1_2)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.frame_8 = QtWidgets.QFrame(parent=self.leftw1_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_35.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.Signup_2 = QtWidgets.QPushButton(parent=self.frame_8)
        self.Signup_2.setMinimumSize(QtCore.QSize(211, 111))
        self.Signup_2.setMaximumSize(QtCore.QSize(211, 111))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Signup_2.setFont(font)
        self.Signup_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Signup_2.setMouseTracking(False)
        self.Signup_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Signup_2.setStyleSheet("QPushButton {\n"
"    background-color: #F64C72;\n"
"    border: none;\n"
"    color:white;\n"
"    padding-top: 40px;\n"
"border-radius: 50px;\n"
"padding-bottom: 40px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(207, 64, 97);\n"
"}\n"
"\n"
"Color: light-grey;")
        self.Signup_2.setCheckable(False)
        self.Signup_2.setFlat(False)
        self.Signup_2.setObjectName("Signup_2")
        self.gridLayout_35.addWidget(self.Signup_2, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.frame_8, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.leftw1_2, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leftw3_3 = QtWidgets.QWidget(parent=self.leftside)
        self.leftw3_3.setMinimumSize(QtCore.QSize(419, 154))
        self.leftw3_3.setMaximumSize(QtCore.QSize(419, 154))
        self.leftw3_3.setStyleSheet("border-color:rgba(58, 60, 211,200);")
        self.leftw3_3.setObjectName("leftw3_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.leftw3_3)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.widget_17 = QtWidgets.QWidget(parent=self.leftw3_3)
        self.widget_17.setMinimumSize(QtCore.QSize(111, 132))
        self.widget_17.setMaximumSize(QtCore.QSize(111, 132))
        self.widget_17.setStyleSheet("QPushButton {\n"
"    background-color:   rgb(9, 78, 116);\n"
"    border: none;\n"
"    color:white;\n"
"    padding-top: 40px;\n"
"border-radius: 30px;\n"
"padding-bottom: 40px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(12, 116, 172);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(7, 67, 99);\n"
"}")
        self.widget_17.setObjectName("widget_17")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.widget_17)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.Quitter_2 = QtWidgets.QPushButton(parent=self.widget_17)
        self.Quitter_2.setMinimumSize(QtCore.QSize(89, 110))
        self.Quitter_2.setMaximumSize(QtCore.QSize(89, 110))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.Quitter_2.setFont(font)
        self.Quitter_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Quitter_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:rgb(63, 66, 232);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        self.Quitter_2.setObjectName("Quitter_2")
        self.gridLayout_37.addWidget(self.Quitter_2, 0, 0, 1, 1)
        self.horizontalLayout_21.addWidget(self.widget_17)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.gridLayout_38.addWidget(self.leftw3_3, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_38.addItem(spacerItem7, 3, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_38.addItem(spacerItem8, 1, 0, 1, 1)
        self.gridLayout_33.addWidget(self.leftside, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(parent=self.widget_16)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.rightside = QtWidgets.QWidget(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightside.sizePolicy().hasHeightForWidth())
        self.rightside.setSizePolicy(sizePolicy)
        self.rightside.setStyleSheet("background-color: rgba(58, 60, 211,200);\n"
"border-radius:40px\n"
"")
        self.rightside.setObjectName("rightside")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.rightside)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.rightw1_2 = QtWidgets.QWidget(parent=self.rightside)
        self.rightw1_2.setMinimumSize(QtCore.QSize(418, 183))
        self.rightw1_2.setMaximumSize(QtCore.QSize(418, 183))
        self.rightw1_2.setObjectName("rightw1_2")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.rightw1_2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_11 = QtWidgets.QFrame(parent=self.rightw1_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_40.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.Login_2 = QtWidgets.QPushButton(parent=self.frame_11)
        self.Login_2.setMinimumSize(QtCore.QSize(211, 111))
        self.Login_2.setMaximumSize(QtCore.QSize(211, 111))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Login_2.setFont(font)
        self.Login_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Login_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Login_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #F64C72;\n"
"    border: none;\n"
"    color:white;\n"
"    padding-top: 40px;\n"
"border-radius: 50px;\n"
"padding-bottom: 40px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(207, 64, 97);\n"
"}\n"
"\n"
"Color: light-grey;")
        self.Login_2.setCheckable(False)
        self.Login_2.setFlat(False)
        self.Login_2.setObjectName("Login_2")
        self.gridLayout_40.addWidget(self.Login_2, 0, 0, 1, 1)
        self.horizontalLayout_22.addWidget(self.frame_11)
        self.gridLayout_44.addWidget(self.rightw1_2, 0, 0, 1, 1)
        self.rightw2_2 = QtWidgets.QWidget(parent=self.rightside)
        self.rightw2_2.setObjectName("rightw2_2")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.rightw2_2)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.mdplog_2 = QtWidgets.QLineEdit(parent=self.rightw2_2)
        self.mdplog_2.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.mdplog_2.setFont(font)
        self.mdplog_2.setStyleSheet("background-color: #FFFFFF;")
        self.mdplog_2.setObjectName("mdplog_2")
        self.gridLayout_41.addWidget(self.mdplog_2, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.rightw2_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:red")
        self.label_2.setObjectName("label_2")
        self.gridLayout_41.addWidget(self.label_2, 4, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_41.addItem(spacerItem9, 6, 0, 1, 1)
        self.emaillog_2 = QtWidgets.QLineEdit(parent=self.rightw2_2)
        self.emaillog_2.setMaximumSize(QtCore.QSize(251, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.emaillog_2.setFont(font)
        self.emaillog_2.setStyleSheet("background-color: #FFFFFF;")
        self.emaillog_2.setObjectName("emaillog_2")
        self.gridLayout_41.addWidget(self.emaillog_2, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_41.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_41.addItem(spacerItem11, 5, 0, 1, 1)
        self.gridLayout_44.addWidget(self.rightw2_2, 1, 0, 1, 1)
        self.gridLayout_39.addWidget(self.rightside, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.frame_7)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.gridLayout_32.addWidget(self.widget_16, 0, 0, 1, 1)
        self.LIVRE.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.widget_4 = QtWidgets.QWidget(parent=self.page_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame = QtWidgets.QFrame(parent=self.widget_4)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.leftmenu_3 = QtWidgets.QWidget(parent=self.frame)
        self.leftmenu_3.setStyleSheet("#leftmenu{\n"
"background-color : rgb(9,78,116);\n"
"}")
        self.leftmenu_3.setObjectName("leftmenu_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.leftmenu_3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_9 = QtWidgets.QFrame(parent=self.leftmenu_3)
        self.frame_9.setStyleSheet("background-color: rgba(58, 60, 211,200);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.leftsubmenu_3 = QtWidgets.QWidget(parent=self.frame_9)
        self.leftsubmenu_3.setStyleSheet("#leftmenu{\n"
"background-color : rgb(9,78,116);\n"
"}")
        self.leftsubmenu_3.setObjectName("leftsubmenu_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.leftsubmenu_3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.leftsubmenu_4 = QtWidgets.QWidget(parent=self.leftsubmenu_3)
        self.leftsubmenu_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.leftsubmenu_4.setObjectName("leftsubmenu_4")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.leftsubmenu_4)
        self.gridLayout_25.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_25.setSpacing(5)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.frame_16 = QtWidgets.QFrame(parent=self.leftsubmenu_4)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.DisconnectBtn_3 = QtWidgets.QPushButton(parent=self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.DisconnectBtn_3.setFont(font)
        self.DisconnectBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.DisconnectBtn_3.setStyleSheet("QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/log-out.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.DisconnectBtn_3.setIcon(icon5)
        self.DisconnectBtn_3.setObjectName("DisconnectBtn_3")
        self.verticalLayout_22.addWidget(self.DisconnectBtn_3)
        self.gridLayout_25.addWidget(self.frame_16, 5, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(parent=self.leftsubmenu_4)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_26.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_26.setSpacing(5)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.ActivitiesBtn_3 = QtWidgets.QPushButton(parent=self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.ActivitiesBtn_3.setFont(font)
        self.ActivitiesBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ActivitiesBtn_3.setStyleSheet("QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/dribbble.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ActivitiesBtn_3.setIcon(icon6)
        self.ActivitiesBtn_3.setObjectName("ActivitiesBtn_3")
        self.gridLayout_26.addWidget(self.ActivitiesBtn_3, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.frame_15, 3, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(parent=self.leftsubmenu_4)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.HomeBtn_3 = QtWidgets.QPushButton(parent=self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.HomeBtn_3.setFont(font)
        self.HomeBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.HomeBtn_3.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HomeBtn_3.setIcon(icon7)
        self.HomeBtn_3.setObjectName("HomeBtn_3")
        self.verticalLayout_14.addWidget(self.HomeBtn_3)
        self.gridLayout_25.addWidget(self.frame_14, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_25.addItem(spacerItem13, 2, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_25.addItem(spacerItem14, 4, 0, 1, 1)
        self.nomprenomlabel_3 = QtWidgets.QLabel(parent=self.leftsubmenu_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nomprenomlabel_3.setFont(font)
        self.nomprenomlabel_3.setText("")
        self.nomprenomlabel_3.setObjectName("nomprenomlabel_3")
        self.gridLayout_25.addWidget(self.nomprenomlabel_3, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.leftsubmenu_4)
        self.gridLayout_24.addWidget(self.leftsubmenu_3, 0, 0, 1, 1)
        self.horizontalLayout_17.addWidget(self.frame_9, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.gridLayout_27.addWidget(self.leftmenu_3, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_12.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget_4)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.rightmainmenu = QtWidgets.QWidget(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightmainmenu.sizePolicy().hasHeightForWidth())
        self.rightmainmenu.setSizePolicy(sizePolicy)
        self.rightmainmenu.setObjectName("rightmainmenu")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.rightmainmenu)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rightleftmenu = QtWidgets.QWidget(parent=self.rightmainmenu)
        self.rightleftmenu.setMinimumSize(QtCore.QSize(416, 639))
        self.rightleftmenu.setObjectName("rightleftmenu")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rightleftmenu)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_5 = QtWidgets.QWidget(parent=self.rightleftmenu)
        self.widget_5.setMinimumSize(QtCore.QSize(354, 617))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.Prenom_nom = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.Prenom_nom.setFont(font)
        self.Prenom_nom.setStyleSheet("color: black")
        self.Prenom_nom.setObjectName("Prenom_nom")
        self.gridLayout_13.addWidget(self.Prenom_nom, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.widget_6, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(324, 530))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.line_8 = QtWidgets.QFrame(parent=self.widget_7)
        self.line_8.setStyleSheet("background-color: rgb(246, 76, 114)")
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_12.addWidget(self.line_8)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_12.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.scroll_activities = QtWidgets.QScrollArea(parent=self.widget_9)
        self.scroll_activities.setStyleSheet("\n"
"\n"
"background-color: rgba(58, 60, 211,200);\n"
"border:none;\n"
"border-radius:40px;")
        self.scroll_activities.setWidgetResizable(True)
        self.scroll_activities.setObjectName("scroll_activities")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 610, 461))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widgetool = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widgetool.setMinimumSize(QtCore.QSize(541, 141))
        self.widgetool.setMaximumSize(QtCore.QSize(16777215, 141))
        self.widgetool.setStyleSheet("")
        self.widgetool.setObjectName("widgetool")
        self.toolButton = QtWidgets.QToolButton(parent=self.widgetool)
        self.toolButton.setGeometry(QtCore.QRect(0, 10, 541, 131))
        self.toolButton.setStyleSheet("background-color: rgb(20, 174, 182);\n"
"border-radius:25px;\n"
"")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.label_4 = QtWidgets.QLabel(parent=self.widgetool)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(32)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 32pt \"Arial\";\n"
"border-radius: 30px;\n"
"border: 0.5px solid rgb(0,0,0);\n"
"border:none;")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.widgetool)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 251, 16))
        self.label_7.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(11, 107, 159);\n"
"color: white;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.widgetool)
        self.widgetool_2 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widgetool_2.setMinimumSize(QtCore.QSize(541, 141))
        self.widgetool_2.setMaximumSize(QtCore.QSize(16777215, 141))
        self.widgetool_2.setObjectName("widgetool_2")
        self.toolButton_10 = QtWidgets.QToolButton(parent=self.widgetool_2)
        self.toolButton_10.setGeometry(QtCore.QRect(0, 10, 541, 131))
        self.toolButton_10.setStyleSheet("background-color: rgb(20, 174, 182);\n"
"border-radius:25px;")
        self.toolButton_10.setText("")
        self.toolButton_10.setObjectName("toolButton_10")
        self.label_19 = QtWidgets.QLabel(parent=self.widgetool_2)
        self.label_19.setGeometry(QtCore.QRect(20, 20, 141, 61))
        self.label_19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 32pt \"Arial\";\n"
"border-radius: 30px;\n"
"border: 0.5px solid rgb(0,0,0);\n"
"border:none;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.widgetool_2)
        self.label_20.setGeometry(QtCore.QRect(20, 100, 251, 16))
        self.label_20.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(11, 107, 159);\n"
"color: white;")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_13.addWidget(self.widgetool_2)
        self.widgetool_3 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widgetool_3.setMinimumSize(QtCore.QSize(541, 141))
        self.widgetool_3.setMaximumSize(QtCore.QSize(16777215, 141))
        self.widgetool_3.setObjectName("widgetool_3")
        self.toolButton_11 = QtWidgets.QToolButton(parent=self.widgetool_3)
        self.toolButton_11.setGeometry(QtCore.QRect(0, 10, 541, 131))
        self.toolButton_11.setStyleSheet("background-color: rgb(20, 174, 182);\n"
"border-radius:25px;")
        self.toolButton_11.setText("")
        self.toolButton_11.setObjectName("toolButton_11")
        self.label_21 = QtWidgets.QLabel(parent=self.widgetool_3)
        self.label_21.setGeometry(QtCore.QRect(20, 20, 141, 61))
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 32pt \"Arial\";\n"
"border-radius: 30px;\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.widgetool_3)
        self.label_22.setGeometry(QtCore.QRect(20, 100, 251, 16))
        self.label_22.setStyleSheet("font: 75 10pt \"Arial\";\n"
"background-color: rgb(11, 107, 159);\n"
"color: white;")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_13.addWidget(self.widgetool_3)
        self.scroll_activities.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_15.addWidget(self.scroll_activities, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.widget_9)
        self.gridLayout_12.addWidget(self.widget_7, 1, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.widget_5)
        self.horizontalLayout_13.addWidget(self.rightleftmenu)
        self.gridLayout_23.addWidget(self.rightmainmenu, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_2)
        self.gridLayout_11.addWidget(self.widget_4, 0, 0, 1, 1)
        self.LIVRE.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.widget_21 = QtWidgets.QWidget(parent=self.page_4)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_12 = QtWidgets.QFrame(parent=self.widget_21)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.mainbodycontainer = QtWidgets.QWidget(parent=self.frame_12)
        self.mainbodycontainer.setStyleSheet("background-color: rgba(58, 60, 211,200);")
        self.mainbodycontainer.setObjectName("mainbodycontainer")
        self.gridLayout_50 = QtWidgets.QGridLayout(self.mainbodycontainer)
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.leftmenu = QtWidgets.QWidget(parent=self.mainbodycontainer)
        self.leftmenu.setStyleSheet("#leftmenu{\n"
"background-color :none;\n"
"}")
        self.leftmenu.setObjectName("leftmenu")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.leftmenu)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.leftsubmenu = QtWidgets.QWidget(parent=self.leftmenu)
        self.leftsubmenu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.leftsubmenu.setStyleSheet("background-color:none")
        self.leftsubmenu.setObjectName("leftsubmenu")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.leftsubmenu)
        self.gridLayout_47.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_47.setSpacing(5)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.frame_28 = QtWidgets.QFrame(parent=self.leftsubmenu)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.HomeBtn = QtWidgets.QPushButton(parent=self.frame_28)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.HomeBtn.setFont(font)
        self.HomeBtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.HomeBtn.setIcon(icon7)
        self.HomeBtn.setDefault(True)
        self.HomeBtn.setObjectName("HomeBtn")
        self.verticalLayout_19.addWidget(self.HomeBtn)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_19.addItem(spacerItem15)
        self.gridLayout_47.addWidget(self.frame_28, 1, 0, 1, 1)
        self.frame_30 = QtWidgets.QFrame(parent=self.leftsubmenu)
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.DisconnectBtn = QtWidgets.QPushButton(parent=self.frame_30)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.DisconnectBtn.setFont(font)
        self.DisconnectBtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.DisconnectBtn.setIcon(icon5)
        self.DisconnectBtn.setObjectName("DisconnectBtn")
        self.verticalLayout_20.addWidget(self.DisconnectBtn)
        self.gridLayout_47.addWidget(self.frame_30, 5, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_47.addItem(spacerItem16, 4, 0, 1, 1)
        self.frame_29 = QtWidgets.QFrame(parent=self.leftsubmenu)
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_48.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_48.setSpacing(5)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.ActivitiesBtn = QtWidgets.QPushButton(parent=self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.ActivitiesBtn.setFont(font)
        self.ActivitiesBtn.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.ActivitiesBtn.setIcon(icon6)
        self.ActivitiesBtn.setObjectName("ActivitiesBtn")
        self.gridLayout_48.addWidget(self.ActivitiesBtn, 1, 0, 1, 1)
        self.gridLayout_47.addWidget(self.frame_29, 3, 0, 1, 1)
        self.nomprenomlabel = QtWidgets.QLabel(parent=self.leftsubmenu)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nomprenomlabel.setFont(font)
        self.nomprenomlabel.setStyleSheet("color:rgb(208, 208, 208)\n"
"\n"
"")
        self.nomprenomlabel.setText("")
        self.nomprenomlabel.setObjectName("nomprenomlabel")
        self.gridLayout_47.addWidget(self.nomprenomlabel, 0, 0, 1, 1)
        self.horizontalLayout_30.addWidget(self.leftsubmenu)
        self.gridLayout_50.addWidget(self.leftmenu, 0, 0, 1, 1)
        self.gridLayout_49.addWidget(self.mainbodycontainer, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_24.addWidget(self.frame_12, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_13 = QtWidgets.QFrame(parent=self.widget_21)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.widget_22 = QtWidgets.QWidget(parent=self.frame_13)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_24 = QtWidgets.QFrame(parent=self.widget_22)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem17)
        self.TennisBtn = QtWidgets.QPushButton(parent=self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.TennisBtn.sizePolicy().hasHeightForWidth())
        self.TennisBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.TennisBtn.setFont(font)
        self.TennisBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/tennis logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.TennisBtn.setIcon(icon8)
        self.TennisBtn.setIconSize(QtCore.QSize(64, 64))
        self.TennisBtn.setObjectName("TennisBtn")
        self.horizontalLayout_25.addWidget(self.TennisBtn)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem18)
        self.line = QtWidgets.QFrame(parent=self.frame_24)
        self.line.setStyleSheet("background-color: #F64C72")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_25.addWidget(self.line)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem19)
        self.BasketBtn = QtWidgets.QPushButton(parent=self.frame_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.BasketBtn.sizePolicy().hasHeightForWidth())
        self.BasketBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.BasketBtn.setFont(font)
        self.BasketBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.BasketBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/ballon basket.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BasketBtn.setIcon(icon9)
        self.BasketBtn.setIconSize(QtCore.QSize(64, 64))
        self.BasketBtn.setObjectName("BasketBtn")
        self.horizontalLayout_25.addWidget(self.BasketBtn)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem20)
        self.verticalLayout_10.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(parent=self.widget_22)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem21)
        self.GolfBtn = QtWidgets.QPushButton(parent=self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.GolfBtn.sizePolicy().hasHeightForWidth())
        self.GolfBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.GolfBtn.setFont(font)
        self.GolfBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/golf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.GolfBtn.setIcon(icon10)
        self.GolfBtn.setIconSize(QtCore.QSize(64, 64))
        self.GolfBtn.setObjectName("GolfBtn")
        self.horizontalLayout_26.addWidget(self.GolfBtn)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem22)
        self.line_4 = QtWidgets.QFrame(parent=self.frame_25)
        self.line_4.setStyleSheet("background-color: #F64C72")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_26.addWidget(self.line_4)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem23)
        self.HikingBtn = QtWidgets.QPushButton(parent=self.frame_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.HikingBtn.sizePolicy().hasHeightForWidth())
        self.HikingBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.HikingBtn.setFont(font)
        self.HikingBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.HikingBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/hiking.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HikingBtn.setIcon(icon11)
        self.HikingBtn.setIconSize(QtCore.QSize(64, 64))
        self.HikingBtn.setObjectName("HikingBtn")
        self.horizontalLayout_26.addWidget(self.HikingBtn)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem24)
        self.verticalLayout_10.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(parent=self.widget_22)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem25)
        self.KayakBtn = QtWidgets.QPushButton(parent=self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.KayakBtn.sizePolicy().hasHeightForWidth())
        self.KayakBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.KayakBtn.setFont(font)
        self.KayakBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/kayaking-png.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.KayakBtn.setIcon(icon12)
        self.KayakBtn.setIconSize(QtCore.QSize(64, 64))
        self.KayakBtn.setObjectName("KayakBtn")
        self.horizontalLayout_28.addWidget(self.KayakBtn)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem26)
        self.line_5 = QtWidgets.QFrame(parent=self.frame_26)
        self.line_5.setStyleSheet("background-color :#F64C72")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_28.addWidget(self.line_5)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem27)
        self.JetskiBtn = QtWidgets.QPushButton(parent=self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.JetskiBtn.sizePolicy().hasHeightForWidth())
        self.JetskiBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.JetskiBtn.setFont(font)
        self.JetskiBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.JetskiBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/jet ski.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.JetskiBtn.setIcon(icon13)
        self.JetskiBtn.setIconSize(QtCore.QSize(70, 70))
        self.JetskiBtn.setObjectName("JetskiBtn")
        self.horizontalLayout_28.addWidget(self.JetskiBtn)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem28)
        self.verticalLayout_10.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(parent=self.widget_22)
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem29)
        self.HammamBtn = QtWidgets.QPushButton(parent=self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.HammamBtn.sizePolicy().hasHeightForWidth())
        self.HammamBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.HammamBtn.setFont(font)
        self.HammamBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/hammam.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.HammamBtn.setIcon(icon14)
        self.HammamBtn.setIconSize(QtCore.QSize(64, 64))
        self.HammamBtn.setObjectName("HammamBtn")
        self.horizontalLayout_29.addWidget(self.HammamBtn)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem30)
        self.line_6 = QtWidgets.QFrame(parent=self.frame_27)
        self.line_6.setStyleSheet("background-color: #F64C72")
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_29.addWidget(self.line_6)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem31)
        self.MassageBtn = QtWidgets.QPushButton(parent=self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.MassageBtn.sizePolicy().hasHeightForWidth())
        self.MassageBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(30)
        self.MassageBtn.setFont(font)
        self.MassageBtn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.MassageBtn.setStyleSheet("QPushButton {\n"
"    background-color:rgb(69, 75, 255);\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius:40px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 74, 253);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(51, 56, 191);\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/images/massage.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.MassageBtn.setIcon(icon15)
        self.MassageBtn.setIconSize(QtCore.QSize(64, 64))
        self.MassageBtn.setObjectName("MassageBtn")
        self.horizontalLayout_29.addWidget(self.MassageBtn)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem32)
        self.verticalLayout_10.addWidget(self.frame_27)
        self.gridLayout_46.addWidget(self.widget_22, 0, 0, 1, 1)
        self.horizontalLayout_24.addWidget(self.frame_13)
        self.gridLayout_45.addWidget(self.widget_21, 0, 0, 1, 1)
        self.LIVRE.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_2 = QtWidgets.QWidget(parent=self.page_5)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Framemenu = QtWidgets.QFrame(parent=self.widget_2)
        self.Framemenu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Framemenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Framemenu.setObjectName("Framemenu")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.Framemenu)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_3 = QtWidgets.QWidget(parent=self.Framemenu)
        self.widget_3.setStyleSheet("background-color: rgba(58, 60, 211,200);")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.leftmenu_2 = QtWidgets.QWidget(parent=self.widget_3)
        self.leftmenu_2.setStyleSheet("#leftmenu{\n"
"background-color : rgb(9,78,116);\n"
"}")
        self.leftmenu_2.setObjectName("leftmenu_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.leftmenu_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.leftsubmenu_2 = QtWidgets.QWidget(parent=self.leftmenu_2)
        self.leftsubmenu_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.leftsubmenu_2.setObjectName("leftsubmenu_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.leftsubmenu_2)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem33, 4, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(parent=self.leftsubmenu_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.DisconnectBtn_2 = QtWidgets.QPushButton(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.DisconnectBtn_2.setFont(font)
        self.DisconnectBtn_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.DisconnectBtn_2.setIcon(icon5)
        self.DisconnectBtn_2.setObjectName("DisconnectBtn_2")
        self.verticalLayout_7.addWidget(self.DisconnectBtn_2)
        self.gridLayout_5.addWidget(self.frame_6, 5, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.leftsubmenu_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ActivitiesBtn_2 = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.ActivitiesBtn_2.setFont(font)
        self.ActivitiesBtn_2.setStyleSheet("QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.ActivitiesBtn_2.setIcon(icon6)
        self.ActivitiesBtn_2.setObjectName("ActivitiesBtn_2")
        self.gridLayout_6.addWidget(self.ActivitiesBtn_2, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_5, 3, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.leftsubmenu_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.HomeBtn_2 = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.HomeBtn_2.setFont(font)
        self.HomeBtn_2.setStyleSheet("QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        self.HomeBtn_2.setIcon(icon7)
        self.HomeBtn_2.setObjectName("HomeBtn_2")
        self.verticalLayout_5.addWidget(self.HomeBtn_2)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem34)
        self.gridLayout_5.addWidget(self.frame_4, 1, 0, 1, 1)
        self.nomprenomlabel_2 = QtWidgets.QLabel(parent=self.leftsubmenu_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.nomprenomlabel_2.setFont(font)
        self.nomprenomlabel_2.setStyleSheet("color:rgb(208, 208, 208)\n"
"\n"
"")
        self.nomprenomlabel_2.setText("")
        self.nomprenomlabel_2.setObjectName("nomprenomlabel_2")
        self.gridLayout_5.addWidget(self.nomprenomlabel_2, 0, 0, 1, 1)
        self.horizontalLayout_16.addWidget(self.leftsubmenu_2)
        self.gridLayout_7.addWidget(self.leftmenu_2, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.widget_3, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.Framemenu)
        self.frameactchoix = QtWidgets.QFrame(parent=self.widget_2)
        self.frameactchoix.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameactchoix.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameactchoix.setObjectName("frameactchoix")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frameactchoix)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Activites2 = QtWidgets.QWidget(parent=self.frameactchoix)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setBold(True)
        font.setWeight(75)
        self.Activites2.setFont(font)
        self.Activites2.setStyleSheet("background-color:none")
        self.Activites2.setObjectName("Activites2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Activites2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TITREACT_label = QtWidgets.QLabel(parent=self.Activites2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TITREACT_label.sizePolicy().hasHeightForWidth())
        self.TITREACT_label.setSizePolicy(sizePolicy)
        self.TITREACT_label.setMaximumSize(QtCore.QSize(901, 13))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.TITREACT_label.setFont(font)
        self.TITREACT_label.setStyleSheet("color : rgb(255, 255, 255); \n"
"")
        self.TITREACT_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.TITREACT_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.TITREACT_label.setScaledContents(False)
        self.TITREACT_label.setWordWrap(False)
        self.TITREACT_label.setObjectName("TITREACT_label")
        self.gridLayout_3.addWidget(self.TITREACT_label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_10 = QtWidgets.QFrame(parent=self.Activites2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.widget_12 = QtWidgets.QWidget(parent=self.frame_10)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.line_3 = QtWidgets.QFrame(parent=self.widget_12)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setStyleSheet("background-color: rgb(246, 76, 114);")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_17.addWidget(self.line_3, 1, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(parent=self.widget_12)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.widget_13 = QtWidgets.QWidget(parent=self.frame_20)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_21 = QtWidgets.QFrame(parent=self.widget_13)
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.calendrieract = QtWidgets.QCalendarWidget(parent=self.frame_21)
        self.calendrieract.setMinimumSize(QtCore.QSize(312, 183))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        self.calendrieract.setFont(font)
        self.calendrieract.setStyleSheet("#calendarWidget QWidget {\n"
"    alternate-background-color:#B8E2FF;\n"
"}\n"
"\n"
"#qt_calendar_ navigationbar{\n"
"    background-color: #fff;\n"
"    border: 2px solid #B8E2FF;\n"
"    border-bottom : 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius:5px;\n"
"}\n"
"\n"
"#qt_calendar_premonth,\n"
"#qt_calendar_nextmonth{\n"
"    border:none;\n"
"    min-width:13px;\n"
"    max-width:13px;\n"
"    min-height:13px;\n"
"    max-height:13px;\n"
"    border-radius:5px;\n"
"    background-color:transparent;\n"
"    padding:5px;\n"
"}\n"
"\n"
"\n"
"#qt_calendarprevmonth{\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"#qt_calendarnextmonth{\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth:hover,\n"
"#qt_calendar_nextmonth:hover{\n"
"    background-color:#55aaff;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth:pressed,\n"
"#qt_calendar_nextmonth:pressed{\n"
"    background-color:#55aaff;\n"
"}\n"
"\n"
"\n"
"#qt_calendar_yearbutton{\n"
"    color:#000;\n"
"    margin:5px;\n"
"    border-radius:5px;\n"
"    font-size:13px;\n"
"    padding: 0 10px;\n"
"}\n"
"\n"
"#qt_calendar_monthbutton{\n"
"width: 110px;\n"
"color: #000;\n"
"font-size:13px;\n"
"margin: 5px 0;\n"
"border-radius:5px;\n"
"padding:0px 2px;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton:hover,\n"
"#qt_calendar_monthbutton:hover{\n"
"    background-color:#55aaff;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton:pressed,\n"
"#qt_calendar_monthbutton:pressed{\n"
"    background-color:#55aaff;\n"
"}\n"
"\n"
"#qt_calendar_yearedit{\n"
"    min-width:53px;\n"
"    color:#000;\n"
"    background:transparent;\n"
"    font-size:13px;\n"
"\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button{\n"
"    image : url(:/icon/arrow-down-circle.svg);\n"
"    subcontrol-position:right;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::up-button{\n"
"    image :url(:/icon/arrow-up-circle.svg);\n"
"    subcontrol-position:left;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button,\n"
"#qt_calendar_yearedit::up-button{\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    padding: 0px 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button:hover,\n"
"#qt_calendar_yearedit::up-button:hover{\n"
"    background-color:#55aaff;\n"
"\n"
"}\n"
"\n"
"#calendarWidget QtoolButton QMenu{\n"
"    background: #fff;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.calendrieract.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.calendrieract.setObjectName("calendrieract")
        self.gridLayout_19.addWidget(self.calendrieract, 0, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_19.addItem(spacerItem35, 0, 1, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_19.addItem(spacerItem36, 0, 2, 1, 1)
        self.horizontalLayout_14.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(parent=self.widget_13)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_14 = QtWidgets.QWidget(parent=self.frame_22)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_23 = QtWidgets.QFrame(parent=self.widget_14)
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout_20.addWidget(self.frame_23, 0, 1, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.widget_14)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background-color: rgba(58, 60, 211,200);\n"
"border:none;\n"
"border-radius:40px")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout_20.addWidget(self.textBrowser_4, 0, 2, 1, 1)
        self.horizontalLayout_15.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(parent=self.frame_22)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.spinbox_adultes = QtWidgets.QSpinBox(parent=self.widget_15)
        self.spinbox_adultes.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.spinbox_adultes.setMinimum(0)
        self.spinbox_adultes.setMaximum(99)
        self.spinbox_adultes.setProperty("value", 1)
        self.spinbox_adultes.setObjectName("spinbox_adultes")
        self.verticalLayout_18.addWidget(self.spinbox_adultes)
        self.spinbox_enfants = QtWidgets.QSpinBox(parent=self.widget_15)
        self.spinbox_enfants.setObjectName("spinbox_enfants")
        self.verticalLayout_18.addWidget(self.spinbox_enfants)
        self.horizontalLayout_15.addWidget(self.widget_15)
        self.horizontalLayout_14.addWidget(self.frame_22)
        self.gridLayout_18.addWidget(self.widget_13, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_20, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_12, 0, 0, 1, 1)
        self.rechercheBtn = QtWidgets.QPushButton(parent=self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.rechercheBtn.setFont(font)
        self.rechercheBtn.setStyleSheet("QPushButton {\n"
"    background-color:  #F64C72;\n"
"    border: none;\n"
"    padding-top: 5px;\n"
"border-radius: 3.75px;\n"
"padding-bottom: 5px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(255, 103, 131);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(207, 64, 97);\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/search.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rechercheBtn.setIcon(icon16)
        self.rechercheBtn.setObjectName("rechercheBtn")
        self.gridLayout_16.addWidget(self.rechercheBtn, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_10, 1, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(parent=self.Activites2)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.frame_19)
        self.scrollArea_3.setStyleSheet("background-color: rgba(58, 60, 211,200);")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 680, 245))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_15.addWidget(self.scrollArea_3)
        self.gridLayout_3.addWidget(self.frame_19, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.Activites2, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frameactchoix)
        self.gridLayout_9.addWidget(self.widget_2, 0, 0, 1, 1)
        self.LIVRE.addWidget(self.page_5)
        self.gridLayout.addWidget(self.LIVRE, 0, 0, 1, 1)
        PAGES.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=PAGES)
        self.statusbar.setObjectName("statusbar")
        PAGES.setStatusBar(self.statusbar)

        self.retranslateUi(PAGES)
        self.LIVRE.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(PAGES)

    def retranslateUi(self, PAGES):
        _translate = QtCore.QCoreApplication.translate
        PAGES.setWindowTitle(_translate("PAGES", "MainWindow"))
        self.label.setText(_translate("PAGES", "CLUB MEDISEN"))
        self.pushButton.setToolTip(_translate("PAGES", "Login/Signup Page"))
        self.pushButton.setText(_translate("PAGES", "Login/SignUp"))
        self.label_3.setText(_translate("PAGES", "Welcome to Club MEDISEN ! \n"
" Happy Holidays !"))
        self.YoutubeBtn.setToolTip(_translate("PAGES", "Youtube"))
        self.InstagramBtn.setToolTip(_translate("PAGES", "Instagram"))
        self.pushButton_4.setToolTip(_translate("PAGES", "Linkedin"))
        self.twitchBtn.setToolTip(_translate("PAGES", "Twitch"))
        self.nom_2.setPlaceholderText(_translate("PAGES", "Surname"))
        self.emailsu_2.setPlaceholderText(_translate("PAGES", "Email"))
        self.mdpsu_2.setPlaceholderText(_translate("PAGES", "Password"))
        self.prenom_2.setPlaceholderText(_translate("PAGES", "Name"))
        self.textevert.setText(_translate("PAGES", "TextLabel"))
        self.Signup_2.setToolTip(_translate("PAGES", "Sign Up Button"))
        self.Signup_2.setText(_translate("PAGES", "SIGNUP"))
        self.Quitter_2.setToolTip(_translate("PAGES", "Leave to Landing Page"))
        self.Quitter_2.setText(_translate("PAGES", "QUIT"))
        self.Login_2.setToolTip(_translate("PAGES", "Login Button"))
        self.Login_2.setText(_translate("PAGES", "LOGIN"))
        self.mdplog_2.setPlaceholderText(_translate("PAGES", "Password"))
        self.label_2.setText(_translate("PAGES", "Wrong Password or Email ! "))
        self.emaillog_2.setPlaceholderText(_translate("PAGES", "Email"))
        self.frame_16.setToolTip(_translate("PAGES", "Disconnect from the session"))
        self.DisconnectBtn_3.setToolTip(_translate("PAGES", "Disconnect from the app"))
        self.DisconnectBtn_3.setText(_translate("PAGES", "DISCONNECT"))
        self.ActivitiesBtn_3.setToolTip(_translate("PAGES", "Open Activities Page"))
        self.ActivitiesBtn_3.setText(_translate("PAGES", "ACTIVITIES"))
        self.HomeBtn_3.setToolTip(_translate("PAGES", "Go Home"))
        self.HomeBtn_3.setText(_translate("PAGES", "HOME"))
        self.Prenom_nom.setText(_translate("PAGES", "<html><head/><body><p align=\"center\"><span style=\" color:#454bff;\"><br/></span></p><p align=\"center\"><span style=\" font-size:18pt; color:#454bff;\">RESERVATIONS</span></p><p align=\"center\"><span style=\" color:#454bff;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("PAGES", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hdébut - Hfin</span></p></body></html>"))
        self.label_7.setText(_translate("PAGES", "Lieu : 10 rue des vaguelettes"))
        self.label_19.setText(_translate("PAGES", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hdébut - Hfin</span></p></body></html>"))
        self.label_20.setText(_translate("PAGES", "Lieu : 10 rue des vaguelettes"))
        self.label_21.setText(_translate("PAGES", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Hdébut - Hfin</span></p></body></html>"))
        self.label_22.setText(_translate("PAGES", "Lieu : 10 rue des vaguelettes"))
        self.HomeBtn.setToolTip(_translate("PAGES", "Go Home"))
        self.HomeBtn.setText(_translate("PAGES", "HOME"))
        self.frame_30.setToolTip(_translate("PAGES", "Disconnect from the session"))
        self.DisconnectBtn.setToolTip(_translate("PAGES", "Disconnect from the app"))
        self.DisconnectBtn.setText(_translate("PAGES", "DISCONNECT"))
        self.ActivitiesBtn.setToolTip(_translate("PAGES", "Open Activities Page"))
        self.ActivitiesBtn.setText(_translate("PAGES", "ACTIVITIES"))
        self.TennisBtn.setToolTip(_translate("PAGES", "Tennic Activities selector"))
        self.TennisBtn.setText(_translate("PAGES", "TENNIS"))
        self.BasketBtn.setText(_translate("PAGES", "BASKETBALL"))
        self.GolfBtn.setToolTip(_translate("PAGES", "Golf Activities selector"))
        self.GolfBtn.setText(_translate("PAGES", "GOLF"))
        self.HikingBtn.setText(_translate("PAGES", "HIKING "))
        self.KayakBtn.setToolTip(_translate("PAGES", "Kayak Activities selector"))
        self.KayakBtn.setText(_translate("PAGES", "KAYAK"))
        self.JetskiBtn.setText(_translate("PAGES", "JETSKI"))
        self.HammamBtn.setToolTip(_translate("PAGES", "Hammam Activities selector"))
        self.HammamBtn.setText(_translate("PAGES", "HAMMAM"))
        self.MassageBtn.setToolTip(_translate("PAGES", "Massage Activities selector"))
        self.MassageBtn.setText(_translate("PAGES", "MASSAGE"))
        self.frame_6.setToolTip(_translate("PAGES", "Disconnect from the session"))
        self.DisconnectBtn_2.setToolTip(_translate("PAGES", "Disconnect from the app"))
        self.DisconnectBtn_2.setText(_translate("PAGES", "DISCONNECT"))
        self.ActivitiesBtn_2.setToolTip(_translate("PAGES", "Open Activities Page"))
        self.ActivitiesBtn_2.setText(_translate("PAGES", "ACTIVITIES"))
        self.HomeBtn_2.setToolTip(_translate("PAGES", "Go Home"))
        self.HomeBtn_2.setText(_translate("PAGES", "HOME"))
        self.TITREACT_label.setText(_translate("PAGES", "TENNIS"))
        self.line_3.setToolTip(_translate("PAGES", "test "))
        self.textBrowser_4.setHtml(_translate("PAGES", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Rounded MT Bold\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#ffffff;\">Number of adult(s)::</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#ffffff;\">Number of child(en):</span></p></body></html>"))
        self.rechercheBtn.setText(_translate("PAGES", "RESEARCH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PAGES = QtWidgets.QMainWindow()
    ui = Ui_PAGES()
    ui.setupUi(PAGES)
    PAGES.show()
    sys.exit(app.exec())
